### ISSUE TITLE
Clarify result value rendering

### ISSUE THREAD

**Issue by refset** [xtdb/xt-fiddle#17]
Currently:

- top-level strings don't show quotes, can't be differentiated from numbers
- nested strings are double-quoted (vs. single-quoted per SQL) - I guess this counts as JSON too (not just mappy values?)

Not sure what the answers are yet, just noting the inconsistencies.

**Comment by Akeboshiwind** [comment]
Also need to clarify:
- When no results are returned
- When a single row with no cols is returned `[{}]`
