### ISSUE TITLE
strip `;` from the end of a query if it is supplied

### ISSUE THREAD

**Issue by refset** [xtdb/xt-fiddle#24]
Currently a user copying from the docs quickstart (written with xtsql in mind) will be likely to blindly copy-and-paste the query string _including_ the semi-colon.

The `;`-stripping behaviour was consciously added to `xtsql` so that typing/pasting multi-line queries could be supported, similarly to `psql`

**Comment by Akeboshiwind** [comment]
Leaving [this case](https://fiddle.xtdb.com/?version=2.0.0-SNAPSHOT&type=sql&txs=W3sic3lzdGVtLXRpbWUiOm51bGwsInR4cyI6IklOU0VSVCBJTlRPIGRvY3MgKHh0JGlkLCBmb28pIFZBTFVFUyAoMSwgJ2JhcicpIn1d&query=U0VMRUNUIGRvY3MueHQkaWQsIGRvY3MuZm9vIEZST00gZG9jczsgICAKc29tZXRoaW5n) as an error as this is more about compatibility with the quickstart than removing all errors

**Comment by refset** [comment]
Resolved also by https://github.com/xtdb/xtdb/commit/8918064aacde6ff36bed7f0cbd204077e004aad5
