### ISSUE TITLE
Use pgwire instead of the in-process API

### ISSUE THREAD

**Issue by refset** [xtdb/xt-fiddle#42]
Play would be a useful proving ground for pgwire functionality

Benefits:
1. column ordering, NULLs get displayed
2. errors that properly correspond to what users normally see when using pgwire with a local container, and warnings like below
3. stretch goal... the server could potentially even generate literal psql output for the docs :thinking: (might be best for the web UI too, as conversion to JS-types is a bit confusing ("strings" instead of 'strings' etc.)

```
jdt=> select (SELECT sum(_id) FROM docs) WHERE docs._id > 50;
WARNING:  Column not found: docs._id
 _column_1 
-----------
(0 rows)
```

**Comment by johantonelli** [comment]
As far as the UI goes, I'm hearing that you'd prefer (and I agree) something more like [graphiql](https://graphql.github.io/swapi-graphql)
