### ISSUE TITLE
Ensure the README is accurate

### ISSUE THREAD

**Issue by Akeboshiwind** [xtdb/xt-fiddle#8]
Jon tried to run the image and had to use port 8020 but then the buttons didn't work.

We should make sure:
- The fiddle.xtdb.com url is there
- Instructions on how to download and run the docker container
- Dev instructions are accurate for not just me 😓

**Comment by refset** [comment]
This should be enough `docker run -p 3000:8000 --pull-always ghcr.io/xtdb/xt-fiddle`
